### ISSUE TITLE
IncompatibleComposeRuntimeVersionException

### ISSUE THREAD

**Issue by lucgirardin** [tommykw/color-sheet-multiplatform#1]
Hello Ken!

On my machines, the current JS version doesn't compile and spits out the following exception:

```
> Task :common:compileKotlinJs FAILED
e: androidx.compose.compiler.plugins.kotlin.IncompatibleComposeRuntimeVersionException: You are using an outdated version of Compose Runtime that is not compatible with the version of the Compose Compiler plugin you have installed. The compose compiler plugin you are using (version 1.0.0-alpha12) expects a minimum runtime version of 1.0.0-alpha12.
        at androidx.compose.compiler.plugins.kotlin.VersionChecker.outdatedRuntimeWithUnknownVersionNumber(VersionChecker.kt:101)
```
This is the same problem that I described in JetBrains/compose-jb/issues/352. If you ever come with a solution (except using the legacy compiler) or a workaround, please let me know!

Take care,

Luc

**Comment by tommykw** [comment]
Hello Luc!

A similar exception occurred on my machine. Thank you for teaching. I don't know the solution.

**Comment by tommykw** [comment]
Fixed from JS IR compiler to legacy compiler.
https://github.com/tommykw/color-sheet-multiplatform/pull/2
